services:
  springw:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/springwdb
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 # Enables remote debugging
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
